//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioPlus.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_BIBLIOTECAEntities : DbContext
    {
        public DB_BIBLIOTECAEntities()
            : base("name=DB_BIBLIOTECAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTOR> AUTORs { get; set; }
        public virtual DbSet<CATEGORIA> CATEGORIAs { get; set; }
        public virtual DbSet<EDITORIAL> EDITORIALs { get; set; }
        public virtual DbSet<ESTADO_PRESTAMO> ESTADO_PRESTAMO { get; set; }
        public virtual DbSet<LIBRO> LIBROes { get; set; }
        public virtual DbSet<TIPO_PERSONA> TIPO_PERSONA { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        public virtual DbSet<PRESTAMO> PRESTAMOes { get; set; }
        public virtual DbSet<vw_PrestamosRecientes> vw_PrestamosRecientes { get; set; }
        public virtual DbSet<PENALIZACION> PENALIZACIONs { get; set; }
    }
}
