//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioPlus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;


    public partial class LIBRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LIBRO()
        {
            this.ORDEN_COMPRA = new HashSet<ORDEN_COMPRA>();
            this.PRESTAMOes = new HashSet<PRESTAMO>();
        }
        [Display(Name = "ID")]
        public int IdLibro { get; set; }
        [Required(ErrorMessage = "El nombre del título es obligatorio.")]
        [StringLength(255, ErrorMessage = "El nombre no puede exceder los 255 caracteres.")]
        [Display(Name = "Título")]
        public string Titulo { get; set; }
        [Display(Name = "Edición")]
        public string Edicion { get; set; }
        [Display(Name = "Año de publicacion")]
        public Nullable<int> AnioPublicacion { get; set; }
        [Display(Name = "Categoría")]
        public Nullable<int> IdCategoria { get; set; }
        [Display(Name = "Editorial")]
        public Nullable<int> IdEditorial { get; set; }
        [Display(Name = "Autor")]
        public Nullable<int> IdAutor { get; set; }
        public string Estado { get; set; }
        [Display(Name = "Fecha de creación")]
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        [Display(Name = "Stock actual")]
        public Nullable<int> StockActual { get; set; }
    
        public virtual AUTOR AUTOR { get; set; }
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual EDITORIAL EDITORIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ORDEN_COMPRA> ORDEN_COMPRA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRESTAMO> PRESTAMOes { get; set; }
    }
}
