//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioPlus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ORDEN_COMPRA
    {
        [Display(Name = "ID Orden compra")]
        public int IdOrdenCompra { get; set; }
        [Display(Name = "ID Persona")]
        public int IdPersona { get; set; }
        [Display(Name = "ID Libro")]
        public int IdLibro { get; set; }
        public int Cantidad { get; set; }
        [Display(Name = "Fecha de compra")]
        public System.DateTime FechaCompra { get; set; }
        public string Estado { get; set; }
        [Display(Name = "Fecha de creación")]
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual LIBRO LIBRO { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
