//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PENALIZACION
    {
        public int IdPenalizacion { get; set; }
        public Nullable<int> IdPrestamo { get; set; }
        public Nullable<decimal> Monto { get; set; }
        public string Motivo { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<bool> Pagado { get; set; }
    
        public virtual PRESTAMO PRESTAMO { get; set; }
    }
}
