//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioPlus.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PRESTAMO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRESTAMO()
        {
            this.PENALIZACIONs = new HashSet<PENALIZACION>();
        }
        [Display(Name = "ID Prestamo")]
        public int IdPrestamo { get; set; }
        [Display(Name = "ID Estado prestamo")]
        public Nullable<int> IdEstadoPrestamo { get; set; }
        [Display(Name = "ID Persona")]
        public Nullable<int> IdPersona { get; set; }
        [Display(Name = "ID Libro")]
        public Nullable<int> IdLibro { get; set; }
        [Display(Name = "F. Devolución")]
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
        [Display(Name = "F. Devuelto")]
        public Nullable<System.DateTime> FechaConfirmacionDevolucion { get; set; }
        [Display(Name = "Estado entregado")]
        public string EstadoEntregado { get; set; }
        [Display(Name = "Estado recibido ")]
        public string EstadoRecibido { get; set; }
        public Nullable<bool> Estado { get; set; }
        [Display(Name = "F. Creación")]  
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        [Display(Name = "F. Entregado")]
        public Nullable<System.DateTime> FechaEntregado { get; set; }
    
        public virtual ESTADO_PRESTAMO ESTADO_PRESTAMO { get; set; }
        public virtual LIBRO LIBRO { get; set; }
        public virtual Persona Persona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PENALIZACION> PENALIZACIONs { get; set; }
    }
}
