//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BiblioPlus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_PrestamosRecientes
    {
        public int IdPrestamo { get; set; }
        public string Titulo { get; set; }
        public string Lector { get; set; }
        public Nullable<System.DateTime> FechaEntregado { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
    }
}
